# Generated by Django 5.0.2 on 2024-03-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meteo", "0002_location_current_wather"),
    ]

    operations = [
        migrations.CreateModel(
            name="Update_tracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=34)),
                ("last_updated", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name="Current_Wather",
            new_name="Current_weather",
        ),
    ]
