# Generated by Django 5.0.2 on 2024-03-22 12:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meteo", "0003_update_tracker_rename_current_wather_current_weather"),
    ]

    operations = [
        migrations.CreateModel(
            name="Forecats",
            fields=[
                (
                    "current_weather_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="meteo.current_weather",
                    ),
                ),
                ("f_timestamp", models.DateTimeField()),
                (
                    "f_rain",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                    ),
                ),
                (
                    "f_snow",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10000),
                        ],
                    ),
                ),
            ],
            bases=("meteo.current_weather",),
        ),
        migrations.RenameField(
            model_name="current_weather",
            old_name="rain_1h",
            new_name="rain",
        ),
        migrations.RenameField(
            model_name="current_weather",
            old_name="snow_1h",
            new_name="snow",
        ),
    ]
